package Application;

// written by Dawid (Dav) Gorski

import javax.swing.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.text.DecimalFormat;



class exportAsPDF {
    private User user;
    private String fileName;


    exportAsPDF(User u) { // constructor
        this.user = u;
        fileName = user.getUserName() + "UserStockPDF.pdf"; //filename
        writeToPDF();
    }

    private void writeToPDF(){
        String path="";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(j);
        if(x == JFileChooser.APPROVE_OPTION){ // this is so that the user can select where to save the file
            path=j.getSelectedFile().getPath();
        }
        fileName= path + "\\"+fileName;

        Document doc = new Document();
        try {
            PdfWriter writer = PdfWriter.getInstance(doc,new FileOutputStream(fileName));
            doc.open();

            PdfPTable table = new PdfPTable(7);
            table.setSpacingBefore(11f);
            table.setSpacingAfter(11f);
            doc.add(new Paragraph("Email: " +user.getUserName()));
            doc.add(new Paragraph("Current funds: " + String.format("%.2f",user.getFunds())));
            doc.add(new Paragraph("Below is a table containing information about your currently owned stocks. "));
            String[] colNames ={"Stock","Shares","Invested","Sold","Share Value","Current Profits","% Change"};
            for (String s:colNames)
            {
                table.addCell(new PdfPCell(new Paragraph(s)));
            }
            for (Stock stock:user.getAllStocks()){ //write all the shares the user has to a table
                DecimalFormat df = new DecimalFormat("####0.00");

                table.addCell(new PdfPCell(new Paragraph(stock.getName().toLowerCase())));
                table.addCell(new PdfPCell(new Paragraph(df.format(stock.getShares()))));
                table.addCell(new PdfPCell(new Paragraph(df.format(stock.getInvested()))));
                table.addCell(new PdfPCell(new Paragraph(df.format(stock.getSales()))));
                double tempVal = stock.getValue("") * stock.getShares();
                table.addCell(new PdfPCell(new Paragraph(df.format(tempVal))));
                tempVal = tempVal + stock.getSales() - stock.getInvested();
                table.addCell(new PdfPCell(new Paragraph(df.format(tempVal))));
                tempVal += stock.getInvested();
                tempVal = 100 - ((tempVal/stock.getInvested()) * 100);
                if (tempVal > 0)table.addCell(new PdfPCell(new Paragraph((df.format(tempVal)))));
                else table.addCell(new PdfPCell(new Paragraph(df.format(-tempVal))));
            }
            doc.add(table);
            doc.add(new Paragraph("PDF generated by team 32s application. Have a good day!"));
            doc.close();
            writer.close();
            AlertMessage.infoBox("PDF saved!");
        }catch(Exception e){AlertMessage.infoBox(e.toString());}

    }
}
